project:
  type: website
  output-dir: docs
  resources:
    - assets/**

website:
  title: "Jatin Kumar Portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
